### ISSUE TITLE
几个功能建议

### ISSUE THREAD

**Issue by msjsc001** [vipzhicheng/logseq-plugin-mark-map#12]
能否添加一个功能，就是按住shift再点击图标时让脑图在右侧页面中单独打开。

![image](https://user-images.githubusercontent.com/93178788/139641292-46ff5509-36b5-4b2f-b118-30b7a51b0854.png)
另外这个脑图是不是有6个层级的限制，笔记中超过6个层级的都显示不出来，能否取消这个限制让更多层级显示出来。

能不能把超过30字的内容，脑图显示时自动换行，而不是向右衍生成很长的条目

**Comment by vipzhicheng** [comment]
第一个问题：这个限制取消不了，因为上游 render 项目用的是 markdown to mindmap，你也知道 markdown 语法里 header 标记只能到第6级。

第二个问题：也跟上游 render 项目有关，需要上游项目来实现，目前我加了一个 hack，可以截取前N个字符的 block 属性 `mark-map-cut:: 30`，使用起来不是很方便，但比没有强，使用以后，渲染时会截取，鼠标悬浮会出完整文字。

**Comment by msjsc001** [comment]
原来是这样，感谢回复。

**Comment by nap-devotion** [comment]
Hello @vipzhicheng. Thank you for the great plugin!
After some months since the creation of this issue I would like to report a successful attempt to generate a mindmap with more than 5 levels using [Markmap's try-it-out-page](https://markmap.js.org/repl) and the [Visual Studio Code Plug-In](https://marketplace.visualstudio.com/items?itemName=gera2ld.markmap-vscode).

![example](https://user-images.githubusercontent.com/99590972/154146470-5f515947-96ba-4f6f-bab4-a25c8c826eb9.png)

I hope very much, that this circumstance also means, that the plugin will display more than 5 levels in the future(?) :)

**Comment by vipzhicheng** [comment]
Save render solution has same limitation, actually this style can be achieve in current Logseq markmap plugin.

![image](https://user-images.githubusercontent.com/1209538/154295557-05999bec-baaf-4813-a6dc-c89295dd3994.png)

The key is in one block to input the hierarchical list, because it's ilegal to using `-`, you can use `*` instead.

But I still do not suggest this way.

In the latest version, my plugin has supported partial render, you can select a child block as base node to render children markmap, you can also click to child page block and then trigger the markmap using shortcut `ctrl+m ctrl+m`
